// Generated by scripts/build-edge-js.mjs from edge/headcount.ts. Do not edit; copy again to update.
// headcount edge wrapper. Copy this file into a site Worker and wrap the
// Worker's handler:
//
//   import { withHeadcount } from './headcount';
//   export default withHeadcount(handler, { site: 'example.com' });
//
// and add the service binding to the site's wrangler.jsonc:
//
//   "services": [{ "binding": "HEADCOUNT", "service": "headcount", "entrypoint": "Collector" }]
//
// On Cloudflare Pages, use it as Functions middleware (functions/_middleware.ts):
//
//   import { headcountPages } from '../path/to/headcount';
//   export const onRequest = headcountPages({ site: 'example.pages.dev' });
//
// with the same service binding in the Pages project's settings.
//
// For every HTML page it serves, the wrapper reports the request to the
// headcount Worker and adds one same-origin script tag carrying a random page
// id. It also answers its own path prefix (default /_hc): the beacon script,
// the beacon endpoint and the opt-out page. It never blocks or breaks the
// page: without the binding, or on any error, the site's response goes out
// untouched.
export const EDGE_VERSION = 2;
/** Request headers forwarded for bot checks. Cookies and auth never leave the site. */
const FORWARDED_HEADERS = [
  'accept',
  'accept-language',
  'accept-encoding',
  'referer',
  'origin',
  'sec-fetch-dest',
  'sec-fetch-mode',
  'sec-fetch-site',
  'sec-fetch-user',
  'sec-ch-ua',
  'sec-ch-ua-mobile',
  'sec-ch-ua-platform',
  'sec-purpose',
  'purpose',
  'signature-agent',
  'signature-input',
  'signature',
  // Set by an optional Transform Rule from cf.client.bot / cf.verified_bot_category.
  'x-hc-verified-bot',
  'x-hc-bot-category',
];
/** request.cf fields headcount reads. botManagement only exists with Enterprise Bot Management. */
const CF_FIELDS = [
  'asn',
  'asOrganization',
  'country',
  'colo',
  'httpProtocol',
  'tlsVersion',
  'tlsClientCiphersSha1',
  'tlsClientExtensionsSha1',
  'tlsClientHelloLength',
  'clientTcpRtt',
  'verifiedBotCategory',
  'botManagement',
];
const MAX_BEACON_BYTES = 8192;
const OPTOUT_COOKIE = 'hc_optout';
/** How long an isolate keeps the beacon before asking headcount again, so updates spread without a redeploy here. */
const SCRIPT_TTL_MS = 5 * 60_000;
let scriptCache = null;
export function withHeadcount(handler, options) {
  const inner = handler.fetch;
  if (!inner)
    throw new Error('withHeadcount: the wrapped handler has no fetch()');
  return {
    ...handler,
    async fetch(request, env, ctx) {
      // The wrapper only ever passes the original request through.
      return headcountFetch(request, env, ctx, (r) => inner.call(handler, r, env, ctx), options);
    },
  };
}
/**
 * The wrapper as a plain function, for Workers whose default export is a class
 * or that route requests themselves. `next` produces the site's own response.
 */
export async function headcountFetch(request, env, ctx, next, options) {
  const collector = env?.HEADCOUNT;
  if (!collector)
    return next(request);
  const prefix = options.path ?? '/_hc';
  const url = new URL(request.url);
  if (url.pathname.startsWith(prefix + '/')) {
    const own = await ownPath(request, url, collector, ctx, options.site, prefix);
    if (own)
      return own;
  }
  const response = await next(request);
  try {
    if (!isPageView(request, response))
      return response;
    if (hasOptedOut(request)) {
      ctx.waitUntil(collector.optedOut(options.site, Date.now()).catch(() => { }));
      return response;
    }
    const pv = randomId();
    const report = {
      v: EDGE_VERSION,
      site: options.site,
      pv,
      url: request.url,
      status: response.status,
      ts: Date.now(),
      facts: factsOf(request),
    };
    ctx.waitUntil(collector.served(report).catch(() => { }));
    return inject(response, `<script src="${prefix}/s.js" data-pv="${pv}" data-e="${prefix}/e" defer></script>`);
  }
  catch {
    return response;
  }
}
/** The wrapper as Cloudflare Pages Functions middleware: export const onRequest = headcountPages({ site }). */
export function headcountPages(options) {
  return (context) => headcountFetch(context.request, context.env, { waitUntil: (p) => context.waitUntil(p) }, () => context.next(), options);
}
/** True for a browser (or bot) loading an HTML page, as opposed to assets, API calls and app-router fetches. */
export function isPageView(request, response) {
  if (request.method !== 'GET')
    return false;
  const status = response.status;
  if (!((status >= 200 && status < 300) || status === 404 || status === 410))
    return false;
  if (!(response.headers.get('content-type') ?? '').toLowerCase().includes('text/html'))
    return false;
  const dest = request.headers.get('sec-fetch-dest');
  if (dest && dest !== 'document')
    return false;
  // Next.js client navigations and prefetches fetch React payloads, not pages.
  if (request.headers.get('rsc') === '1' || request.headers.has('next-router-prefetch'))
    return false;
  if (request.headers.has('upgrade'))
    return false;
  return true;
}
/** Global Privacy Control, Do Not Track, or the opt-out cookie. */
export function hasOptedOut(request) {
  if (request.headers.get('sec-gpc') === '1' || request.headers.get('dnt') === '1')
    return true;
  const cookie = request.headers.get('cookie') ?? '';
  return new RegExp(`(?:^|;\\s*)${OPTOUT_COOKIE}=1(?:;|$)`).test(cookie);
}
function inject(response, tag) {
  const rewritten = new HTMLRewriter()
    .on('head', {
    element(el) {
      el.append(tag, { html: true });
    },
  })
    .transform(response);
  // Each response now carries its own page id, so validators describing the
  // original body no longer apply.
  const headers = new Headers(rewritten.headers);
  headers.delete('etag');
  headers.delete('last-modified');
  return new Response(rewritten.body, { status: rewritten.status, statusText: rewritten.statusText, headers });
}
async function ownPath(request, url, collector, ctx, site, prefix) {
  const rest = url.pathname.slice(prefix.length);
  if (rest === '/s.js' && request.method === 'GET') {
    if (!scriptCache || scriptCache.site !== site || Date.now() - scriptCache.at > SCRIPT_TTL_MS) {
      try {
        scriptCache = { site, body: await collector.script(site), at: Date.now() };
      }
      catch {
        // An empty script keeps the page free of console errors until headcount is back.
        if (!scriptCache)
          return new Response('', { headers: { 'content-type': 'text/javascript; charset=utf-8', 'cache-control': 'no-store' } });
      }
    }
    return new Response(scriptCache.body, {
      headers: {
        'content-type': 'text/javascript; charset=utf-8',
        'cache-control': 'public, max-age=3600',
        'x-content-type-options': 'nosniff',
      },
    });
  }
  if (rest === '/e' && request.method === 'POST') {
    const length = Number(request.headers.get('content-length') ?? '0');
    if (length > MAX_BEACON_BYTES)
      return new Response(null, { status: 413 });
    if (hasOptedOut(request))
      return new Response(null, { status: 204 });
    const body = await request.text();
    if (body.length > MAX_BEACON_BYTES)
      return new Response(null, { status: 413 });
    const report = { v: EDGE_VERSION, site, body, ts: Date.now(), facts: factsOf(request) };
    ctx.waitUntil(collector.beacon(report).catch(() => { }));
    return new Response(null, { status: 204, headers: { 'cache-control': 'no-store' } });
  }
  if (rest === '/optout') {
    if (request.method === 'POST') {
      const form = await request.formData().catch(() => null);
      const out = form?.get('choice') !== 'in';
      const cookie = out
        ? `${OPTOUT_COOKIE}=1; Path=/; Max-Age=63072000; SameSite=Lax; Secure; HttpOnly`
        : `${OPTOUT_COOKIE}=; Path=/; Max-Age=0; SameSite=Lax; Secure; HttpOnly`;
      return new Response(null, { status: 303, headers: { location: url.pathname, 'set-cookie': cookie, 'cache-control': 'no-store' } });
    }
    if (request.method === 'GET')
      return optOutPage(request, url.pathname);
  }
  return null;
}
function optOutPage(request, action) {
  const signal = request.headers.get('sec-gpc') === '1' || request.headers.get('dnt') === '1';
  const cookie = new RegExp(`(?:^|;\\s*)${OPTOUT_COOKIE}=1(?:;|$)`).test(request.headers.get('cookie') ?? '');
  const status = signal
    ? 'Your browser sends a Global Privacy Control or Do Not Track signal, so your visits are not counted. Nothing else is needed.'
    : cookie
      ? 'You have opted out on this browser. Your visits are not counted.'
      : 'Your visits are currently counted, anonymously.';
  const button = cookie
    ? '<button name="choice" value="in">Count my visits again</button>'
    : '<button name="choice" value="out">Opt out on this browser</button>';
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Analytics opt-out</title>
<style>body{font:16px/1.5 system-ui,sans-serif;max-width:36rem;margin:3rem auto;padding:0 1rem;color:#1a1a1a;background:#fff}@media(prefers-color-scheme:dark){body{color:#eee;background:#141414}}button{font:inherit;padding:.5rem 1rem;cursor:pointer}</style></head>
<body><h1>Analytics opt-out</h1>
<p>This site counts visits with its own privacy-friendly analytics. No cookies or other storage are used for counting, IP addresses are never stored, and only totals are kept.</p>
<p><strong>${status}</strong></p>
${signal ? '' : `<form method="post" action="${action}">${button}</form><p>Opting out stores one small cookie on this browser, only to remember your choice.</p>`}
</body></html>`;
  return new Response(html, {
    headers: {
      'content-type': 'text/html; charset=utf-8',
      'cache-control': 'no-store',
      'content-security-policy': "default-src 'none'; style-src 'unsafe-inline'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'",
      'x-robots-tag': 'noindex',
    },
  });
}
function factsOf(request) {
  const headers = {};
  for (const name of FORWARDED_HEADERS) {
    const value = request.headers.get(name);
    if (value !== null)
      headers[name] = value.slice(0, 512);
  }
  const cf = {};
  const raw = request.cf;
  if (raw)
    for (const key of CF_FIELDS)
      if (raw[key] !== undefined)
        cf[key] = raw[key];
  return {
    ip: request.headers.get('cf-connecting-ip') ?? '',
    ua: (request.headers.get('user-agent') ?? '').slice(0, 512),
    headers,
    cf,
  };
}
/** 128 random bits as 22 base64url characters. */
function randomId() {
  const bytes = crypto.getRandomValues(new Uint8Array(16));
  let bin = '';
  for (const b of bytes)
    bin += String.fromCharCode(b);
  return btoa(bin).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}
